### ISSUE TITLE
Nobody recognizes this issue/error in file lib/attacks/find.py????

### ISSUE THREAD

**Issue by hawaii67** [garrettfoster13/sccmhunter#24]
Nobody recognizes this issue/error in file lib/attacks/find.py????

`import ldap3.utils.conv import escape_filter_chars`

Should be:

`from ldap3.utils.conv import escape_filter_chars
`

PS: and in line 261 was an ident error  :-)

**Comment by bushdav** [comment]
Still facing the same issue

**Comment by garrettfoster13** [comment]
@bushdav I'm not seeing this error anymore. Can you share a screenshot or code snippet to show the issue?

**Comment by bushdav** [comment]
@garrettfoster13 here it is attached
![image](https://github.com/garrettfoster13/sccmhunter/assets/46043867/3a9d32bb-53b8-4bfc-b74f-b469d8855fb4)

**Comment by garrettfoster13** [comment]
Thanks! So that looks like an entirely new issue where there are no members of groups identified that I didn't properly handle errors for.

**Comment by aconite33** [comment]
Was this fixed? I'm getting this error.
