### ISSUE TITLE
pipx compatibility

### ISSUE THREAD

**Issue by Cyb3rC3lt** [garrettfoster13/sccmhunter#25]
First off, excellent tool, thanks very much Garrett.

Any chance you could make this compatible with pipx please so it takes care of managing the virtual env for us? Makes life so much easier.

Thanks again

**Comment by garrettfoster13** [comment]
Hey @Cyb3rC3lt thanks for the request! I've working on an update that will take care of some bug fixes and add some more features so I'll add this feature request to the list.

**Comment by Cyb3rC3lt** [comment]
Thanks very much Garrett. On my tests I tend to get a fresh install of Kali on the clients network so as you know just doing "pipx install" every time is so handy. 

I wish I knew about it earlier to be honest. The amount of times I've broken my build just using pip without a virtual env was crazy given Python dependency management is a bit nuts 😊. Thanks again
