### ISSUE TITLE
Unexpected mimetype in content-type: 'text/html'

### ISSUE THREAD

**Issue by msilvestre714** [garrettfoster13/sccmhunter#27]
Running the sccmhunter.py script as follows:

python3 sccmhunter.py http -u user -p password -dc-ip DC ip -d domain -auto

Returns the following output:

INFO     Found targets from logfile.                                                                                                                                                                
INFO     [+] Found http://redacted/                                                                                                                                          
INFO     [*] User selected auto. Attempting to add a machine account then request policies.                                                                                                         
INFO     [+] computer$ created with password: password
INFO     [*] Atempting to grab policy from sccm                                                                                                                                    
Unexpected mimetype in content-type: 'text/html'

Not sure what is causing the issue here...?

**Comment by garrettfoster13** [comment]
Usually see that when SCCM is configured to require PKI auth for client enrollment

**Comment by msilvestre714** [comment]
> Usually see that when SCCM is configured to require PKI auth for client enrollment. My experience with pulling NAAs from HTTP enrollment has been a "try and see".

Totally understand, I have tried this on two occasions and have seen the same error but it makes sense and I also see it as a "if it works, cool" kind of thing.  Much appreciated!

**Comment by aconite33** [comment]
Is there anyway to submit a PKI certificate in order to capture the NAA from HTTP when this issue happens?

**Comment by garrettfoster13** [comment]
@aconite33 

Yes that's on the roadmap. It's just a matter of getting the dev time available to make it happen.

**Comment by aconite33** [comment]
Fricken awesome. Let me know if there is anything I can do to help with the dev/testing. Ran into this just now and would love to see if we can make it work with PKI.
