### ISSUE TITLE
relay option question

### ISSUE THREAD

**Issue by inkz1337** [garrettfoster13/sccmhunter#28]
Hey Garrett thanks for an awesome tool its been really useful on many engagements. I have just one proposal to improve if not lot of effort is needed. The relay option, you implemented the option to add new computer account which is great but not all the time machine account quota is misconfigured, so I was thinking would it even be possible to utilize coercion(Poldarius Coercer) in order to obtain machine account hashes and then relay it to MECM/SCCM HTTP endpoint and then utilize the sccmwtf.py module to obtain policy file.

**Comment by garrettfoster13** [comment]
Love to hear it! And true that is a limitation if the MAQ is blocking you from doing much with it. About the relay though yes at some point in the future I'd like to implement the relay that @Tw1sm already wrote and is currently a PR for Impacket. If that gets merged I'd likely import the changes to sccmhunter.  That PR is here: https://github.com/fortra/impacket/pull/1425. But yes it is completely possible to coerce the enrollment.

**Comment by inkz1337** [comment]
Oh wasn't aware of that. Great news, thanks!
