### ISSUE TITLE
Error when using the "show -all" command

### ISSUE THREAD

**Issue by dkjajhqu2h3j** [garrettfoster13/sccmhunter#36]
Hi,

Thank you for this tool!

When I use the command `show -all` I get the below error. The root cause seems to be that the earlier enumeration never produced the file groups.csv:
<img width="505" alt="sccmhunter1" src="https://github.com/garrettfoster13/sccmhunter/assets/153735386/fc900674-9554-4677-b402-d794b3fcb7b9">

**Comment by dkjajhqu2h3j** [comment]
Great! Using the dev branch works.

I have a question about the `mssql` command. I can execute it and get the query to add an existing domain user account to the database. This works and I can get the `AdminID` of the account afterwards. However, SCCMHunter does not prompt me to enter the `AdminID` as shown in your screenshot. How is this supposed to work?

**Comment by dkjajhqu2h3j** [comment]
Never mind my question. I actually read the query and saw that it is all done in one command :)

**Comment by garrettfoster13** [comment]
Yes! That was a recent change and I haven't updated the ReadMe just yet. I'm considering having both the 1 liner and the separated commands, do you think that would be useful?
