### ISSUE TITLE
"IndexError" when executing commands in a SCCM database

### ISSUE THREAD

**Issue by dkjajhqu2h3j** [garrettfoster13/sccmhunter#37]
Using the dev branch I have successfully added a domain user account to SCCM's database and supposedly have full administrative rights there. However, using the command `admin` I get a database shell but then things starts to fail. None of the commands I have tested works:

<img width="884" alt="sccmhunter3" src="https://github.com/garrettfoster13/sccmhunter/assets/153735386/46b13d42-c398-47bb-9af1-630bde732433">

**Comment by garrettfoster13** [comment]
Yes I need to add a wiki for this module. So essentially the flow would be like this:

`get_device <device_name>` i.e., "PC1"

<img width="656" alt="Cursor_and_root_DEKSTOP-2QO0YEUW___" src="https://github.com/garrettfoster13/sccmhunter/assets/82191679/895936a6-9a06-4eb8-bd06-9cccd58922ba">

Copy the ResourceID

`interact <ResourceID>`

Now issue commands. 

<img width="1354" alt="Cursor_and_root_DEKSTOP-2QO0YEUW___" src="https://github.com/garrettfoster13/sccmhunter/assets/82191679/92cfb74e-f10e-4cd1-a7a0-1a8db638aad5">

**Comment by dkjajhqu2h3j** [comment]
I got a bit further using your help however `ipconfig` still fails/never executes. I should mention that none of the devices I have in SCCM so far have the SCCM client installed if that is important? I am having a hard time getting those to install. Pushing nor pulling the client installation works. Any tips?

<img width="724" alt="sccmhunter1" src="https://github.com/garrettfoster13/sccmhunter/assets/153735386/80d2b570-7282-4d78-a115-c83de2d93289">

**Comment by garrettfoster13** [comment]
Yes the entire module was designed to give you some level of access to enrolled clients via the API so if it's not enrolled it will fail. It looks like you have forest discovery turned on and can see those but did you configure your bondary groups? That might be your limiting factor.
