### ISSUE TITLE
Error binding parameter 1: type 'Entry' is not supported

### ISSUE THREAD

**Issue by HackmichNet** [garrettfoster13/sccmhunter#43]
When running sccm hunter I got the following error:

`ProgrammingError: Error binding parameter 1: type 'Entry' is not supported`

in 

`sccmhunter/lib/attacks/find.py:326 in add_computer_to_db `

In line 315 the code checks if dNSHostName exists in the entry argument. If not, it assignes the "entry" argument as hostname (line 318). This does not work in the later SQL command (line 326).

As workaround I add a return statement in the "else"-condition. Maybe there is a better solution.

**Comment by garrettfoster13** [comment]
Thanks for reporting this issue @HackmichNet. I'm taking a look and think I've narrowed it down to a computer that's trying to be added to the database doesn't have a dnshostname attribute value. I'll get that worked out.

**Comment by ecote7** [comment]
> Thanks for reporting this issue @HackmichNet. I'm taking a look and think I've narrowed it down to a computer that's trying to be added to the database doesn't have a dnshostname attribute value. I'll get that worked out.

I confirm that after adding the "dnshostname" attribute value I don't have the error message on my side.

**Comment by garrettfoster13** [comment]
@ecote7 Thank you for confirming!

**Comment by garrettfoster13** [comment]
Fixed in https://github.com/garrettfoster13/sccmhunter/releases/tag/v1.0.3

Please let me know if you run into any issues!
