### ISSUE TITLE
sccm_data_type

### ISSUE THREAD

**Issue by Zamanry** [garrettfoster13/sccmhunter#52]
Within a Python3.9 virtual environment and after installing the requirements, @TinyTiger08 and I are getting `sccm_data_type` as an error:
![image](https://github.com/garrettfoster13/sccmhunter/assets/28152647/8a41fe5b-57da-486e-a8b0-5dc0f6ccb24a)

Using Kali 2023.3, installed packages:
![image](https://github.com/garrettfoster13/sccmhunter/assets/28152647/763c186d-9691-4e96-978e-3bbfef9d309d)

**Comment by Zamanry** [comment]
Duh, it's due to Match Case statements only being supported in Python >3.10. https://stackoverflow.com/questions/69725962/syntaxerror-invalid-syntax-when-using-match-case

**Comment by garrettfoster13** [comment]
![image](https://github.com/garrettfoster13/sccmhunter/assets/82191679/c02d594b-a4f2-462f-ada6-b28000eb74a4)

**Comment by Invoke-Mimikatz** [comment]
BOOOOO FIX YOUR TOOL

**Comment by Invoke-Mimikatz** [comment]
I dont have Python 3.19 installed

**Comment by garrettfoster13** [comment]
@Invoke-Mimikatz rude
