### ISSUE TITLE
The delete_admin command of the admin function is incorrectly retrieving the adminid

### ISSUE THREAD

**Issue by b0mbard1er** [garrettfoster13/sccmhunter#53]
I found an issue in the delete_admin function of the add_admin.py script.

Line 82 of the add_admin.py script uses the following filter for retrieving the adminid:

`url = f"https://{self.target_ip}/AdminService/wmi/SMS_Admin/?$filter=DisplayName eq '{self.targetuser}'"`

This results in the command not correctly identifying the adminid for a given user, and the command fails with a "Target user is not configured as an SMS Admin". 

Propose swapping the filter on line 82 to:

`url = f"https://{self.target_ip}/AdminService/wmi/SMS_Admin/?$filter=LogonName eq '{self.targetuser}'"`

This matches the filter used in the show_admins command and results in successfully retrieving the adminid for a given target user account.

**Comment by garrettfoster13** [comment]
Hey @b0mbard1er, thanks for the issue! 

I'll take some time this weekend to review the fix but I don't think it will be an issue. Can you describe the scenario you ran into? I'm assuming this was a case where the admin user was confirmed to be an admin yet the 'DisplayName' did not match the 'LogonName'. 

I'd like to avoid a similar issue happening for the opposite case. I'll look into maybe using the `show_admins` command to provide the AdminID and have the delete function operate that way.

**Comment by b0mbard1er** [comment]
Thanks for the quick response! The admin function was used to add a low privilege domain account to the SCCM admin group, confirmed using the show_admins command. This was done using the nt hash of the site server. 

This low privilege account was then used with the admin function to perform several admin operations to confirm admin rights.

The admin function was then used with the site server credential again to remove the low privilege account from the admins group. This was failing with the above error message. I modified the getadminid function in admin.py to swap DisplayName to LogonName and was able to remove the account, with the caveat that the name is entered exactly as was shown with the show_admins command and properly escaped. i.e. "delete_admin DOMAIN\\lowpriv“

As a side note, prior to the modification I made, submitting the delete_admin command with no user specified resulted in the removal of a random Group entity from SCCM admins. Best I can determine is that if no DisplayName attribute exists it may have pulled in the first account. In any case, using LogonName instead of DisplayName should resolve that edge case as well.

Thank you again for your work, this tool has been great to use and has quickly become one of my go-tos!

**Comment by garrettfoster13** [comment]
> submitting the delete_admin command with no user specified resulted in the removal of a random Group entity from SCCM admins

Whoa...that's a concern. Thank you for bringing this up I really appreciate it.

**Comment by garrettfoster13** [comment]
Ok I was able to recreate both of these issues in a lab. Working on a fix...thanks again @b0mbard1er.

**Comment by garrettfoster13** [comment]
Added fixes for these issue sin the latest commit. Thanks again!
