### ISSUE TITLE
Expected string or bytes-like object, got 'NoneType'

### ISSUE THREAD

**Issue by jas594** [garrettfoster13/sccmhunter#62]
Have encountered an issue several times now where device registration fails with the errors "Expected string or bytes-like object, got 'NoneType'" or "Invalid cross-device link". This is using Python v3.11/3.12.

![2024-09-13_16-23-25](https://github.com/user-attachments/assets/64b6770c-9c28-4d07-b3ad-040914296daf)

This is triggered on line: https://github.com/garrettfoster13/sccmhunter/blob/b7a795e6cac0950bb05e0b115635b91fea420a5c/lib/scripts/sccmwtf.py#L315

Not sure if this is fixable within the Python environment itself, but this workaround fixed it:

1. Add import shutil
2. Change os.rename(key, newKey) --> shutil.copy(key, newkey)

**Comment by garrettfoster13** [comment]
@jas594 thanks for bringing this up!

The various errors you're hitting are likely unrelated.

The bytes-like object can be a number of things. Usually a slow database to handle the device registration and to make the policy available so you can try a longer sleep time. 

Nonetype can be related too.

I've tried to address some of these issues in the dev branch if you'd care to give that a shot.

**Comment by jas594** [comment]
Thanks for the quick reply.

> The various errors you're hitting are likely unrelated. 

> 

I thought the same thing and that it was specific to the enrollment endpoint configuration, but the fix I mentioned above did actually fix it for both errors.

> The bytes-like object can be a number of things. Usually a slow database to handle the device registration and to make the policy available so you can try a longer sleep time.

> 
I tried an increased sleep time originally as well, but this did not work. However, it was interesting that the NTLM [relay](https://github.com/fortra/impacket/pull/1425) attack variant worked without errors.

> I've tried to address some of these issues in the dev branch if you'd care to give that a shot.

> 
I can give this a shot next time I encounter the error, but since the fix I mentioned above did the trick, should I submit a pull req for that change?

**Comment by garrettfoster13** [comment]
Sure if you want submit the PR for the change that would be fine. It doesn't appear to be a breaking change and it's used for functionality I doubt many are using. We can make the change and see if anyone yells about it :D.

**Comment by garrettfoster13** [comment]
Fixed in #64

**Comment by l33tluigi** [comment]
This _NoneType_ error seems to still be popping up occasionally, even when the NTLM relay variant works. You mentioned that you've tried to address some of these issues in the dev branch, but I'm not seeing a dev branch. Is it located somewhere else?

**Comment by garrettfoster13** [comment]
The changes were merged into the main branch since then. You're saying you've used the ntlmrelay PR on the same assessment work while sccmhunter did not?

**Comment by l33tluigi** [comment]
Yea exactly

**Comment by garrettfoster13** [comment]
Man this is a pita bug. 

@ville87

Can you help me understand a bit more about the machine you dont see in BH? I wrote the HTTP module to only try machines it's identified are MPs so it's just pulling from that table in the database.

**Comment by ville87** [comment]
In my case it found a management point which is not resolvable via DNS in the client machine nor does exist in AD as a computer object. It is however listed in AD if you search with `(objectclass=mssmsmanagementpoint)` (this is why sccmhunter adds it to the DB).

So for my case, adding a secondary check to lookup if the MP exists as a computer object, would fix the issue that it adds a non existent MP to the DB, in PowerShell that would be something like: 
```powershell
$search = [adsisearcher]"(&(objectclass=mssmsmanagementpoint))"
$search.PageSize = 10000
$mps = $search.FindAll()

foreach($mp in $mps){
  $search = [adsisearcher]"(&(objectclass=computer)(name=$(($($mp.Properties['mssmsmpname']) -split "\.")[0])))"
  $computers = $search.FindAll();
  if(($computers |Measure-Object).count -gt 0){
    "Management Point $($mp.Properties['mssmsmpname'])) exists!"
  }
}
```
Note: In my case even one of the MPs was stored as FQDN in the property `mssmsmpname` and the other only with the hostname, which is why I've added the `($mp.Properties['mssmsmpname']) -split "\.")[0])` to ensure it only takes the hostname to lookup the computerobject, if the mssmsmpname was a FQDN.

This however probably does not fix the error `expected string or bytes-like object, got 'NoneType'` since sccmhunter correctly tries on the specified MP...

**Comment by l33tluigi** [comment]
> <img alt="Image" width="608" src="https://private-user-images.githubusercontent.com/82191679/413773955-a1e97ce4-1c7b-417f-b84f-63157f0fabb7.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzYxMTM2NDksIm5iZiI6MTc3NjExMzM0OSwicGF0aCI6Ii84MjE5MTY3OS80MTM3NzM5NTUtYTFlOTdjZTQtMWM3Yi00MTdmLWI4NGYtNjMxNTdmMGZhYmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDEzVDIwNDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZDUyYmQ4MDhiNGFhYTYxMTE4MDczZDhhY2E5NTA5ZWIzZmUzNDMwNTJlZGI3YWIzMDUxMWQ5OWZkZjZhMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.ImwWppZczSaMqC9ondIyijwhNFh5Q-_ukGi5gHP2BWU">
> Adding this here for my own information later. Believe we can recreate the error user's are seeing by disabling sha256 here and downgrading to sha1 which I suspect is the root cause of this issue.

Were you able to get further on this? Can this bug be re-opened given that users, including myself, are still encountering it?

**Comment by garrettfoster13** [comment]
reopening

**Comment by garrettfoster13** [comment]
@l33tluigi found the culprit, going to need some time to dig into how the encryption is done on the client side 

<img width="1210" height="1210" alt="Image" src="https://github.com/user-attachments/assets/f981b28b-3bd4-4014-9290-556c5bca1917" />
