### ISSUE TITLE
ModuleNotFoundError: No module named 'requests_kerberos'

### ISSUE THREAD

**Issue by QU35T-code** [garrettfoster13/sccmhunter#75]
Hello @garrettfoster13,

Not long ago, you added this code :

* https://github.com/garrettfoster13/sccmhunter/commit/992f8089981c29af2860b99ac7f620537a725091#diff-5e6aa4b5841fb15734744d9af3c580ba638f1ba1bfa6eca1240e43a810219226R8

In this commit, you imported the dependency: `from requests_kerberos import HTTPKerberosAuth`

However, `HTTPKerberosAuth` is not used in the tool and is also not referenced in the `requirements.txt` file. As a result, the tool no longer builds correctly. One solution is to install the missing dependency :

```bash
pip install requests_kerberos
```

Alternatively, if it's not being used, the best approach would be to remove the import.

Cheers

**Comment by garrettfoster13** [comment]
Yeah that shouldn't have made it in, thanks for the call out. It's been removed!
