### ISSUE TITLE
Incorrect version displayed

### ISSUE THREAD

**Issue by xnotsure28x** [garrettfoster13/sccmhunter#77]
Latest release is v1.0.6
https://github.com/garrettfoster13/sccmhunter/releases

Banner has v1.0.5
https://github.com/garrettfoster13/sccmhunter/blob/main/lib/scripts/banner.py#L2

**Comment by xnotsure28x** [comment]
I get this when I try to fix it & do not know how get rid of the `^M`

```
diff --git a/lib/scripts/banner.py b/lib/scripts/banner.py
index c9eb226..aa18ffe 100644
--- a/lib/scripts/banner.py
+++ b/lib/scripts/banner.py
@@ -1,5 +1,5 @@
 
-__version__ = '1.0.5'
+__version__ = '1.0.6'^M
 
 
 def show_banner():
```

**Comment by xnotsure28x** [comment]
PR https://github.com/garrettfoster13/sccmhunter/pull/78 fixes

**Comment by garrettfoster13** [comment]
Fixed 

https://github.com/garrettfoster13/sccmhunter/commit/33c23f0d71e48127a0b03b06a019148df71049ef
